apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: cluster-api-provider-virtink
build:
  local:
    useBuildkit: true
  artifacts:
    - image: capch-controller
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - config/default
