//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkCluster) DeepCopyInto(out *VirTinkCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkCluster.
func (in *VirTinkCluster) DeepCopy() *VirTinkCluster {
	if in == nil {
		return nil
	}
	out := new(VirTinkCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirTinkCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkClusterList) DeepCopyInto(out *VirTinkClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirTinkCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkClusterList.
func (in *VirTinkClusterList) DeepCopy() *VirTinkClusterList {
	if in == nil {
		return nil
	}
	out := new(VirTinkClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirTinkClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkClusterSpec) DeepCopyInto(out *VirTinkClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkClusterSpec.
func (in *VirTinkClusterSpec) DeepCopy() *VirTinkClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VirTinkClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkClusterStatus) DeepCopyInto(out *VirTinkClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkClusterStatus.
func (in *VirTinkClusterStatus) DeepCopy() *VirTinkClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VirTinkClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkMachine) DeepCopyInto(out *VirTinkMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkMachine.
func (in *VirTinkMachine) DeepCopy() *VirTinkMachine {
	if in == nil {
		return nil
	}
	out := new(VirTinkMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirTinkMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkMachineList) DeepCopyInto(out *VirTinkMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirTinkMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkMachineList.
func (in *VirTinkMachineList) DeepCopy() *VirTinkMachineList {
	if in == nil {
		return nil
	}
	out := new(VirTinkMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirTinkMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkMachineSpec) DeepCopyInto(out *VirTinkMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	in.VMSpec.DeepCopyInto(&out.VMSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkMachineSpec.
func (in *VirTinkMachineSpec) DeepCopy() *VirTinkMachineSpec {
	if in == nil {
		return nil
	}
	out := new(VirTinkMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkMachineStatus) DeepCopyInto(out *VirTinkMachineStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkMachineStatus.
func (in *VirTinkMachineStatus) DeepCopy() *VirTinkMachineStatus {
	if in == nil {
		return nil
	}
	out := new(VirTinkMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkMachineTemplate) DeepCopyInto(out *VirTinkMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkMachineTemplate.
func (in *VirTinkMachineTemplate) DeepCopy() *VirTinkMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(VirTinkMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirTinkMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkMachineTemplateList) DeepCopyInto(out *VirTinkMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirTinkMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkMachineTemplateList.
func (in *VirTinkMachineTemplateList) DeepCopy() *VirTinkMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(VirTinkMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirTinkMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkMachineTemplateSpec) DeepCopyInto(out *VirTinkMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkMachineTemplateSpec.
func (in *VirTinkMachineTemplateSpec) DeepCopy() *VirTinkMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(VirTinkMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkMachineTemplateSpecTemplate) DeepCopyInto(out *VirTinkMachineTemplateSpecTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkMachineTemplateSpecTemplate.
func (in *VirTinkMachineTemplateSpecTemplate) DeepCopy() *VirTinkMachineTemplateSpecTemplate {
	if in == nil {
		return nil
	}
	out := new(VirTinkMachineTemplateSpecTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirTinkMachineTemplateStatus) DeepCopyInto(out *VirTinkMachineTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirTinkMachineTemplateStatus.
func (in *VirTinkMachineTemplateStatus) DeepCopy() *VirTinkMachineTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(VirTinkMachineTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
