//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAddressConfig) DeepCopyInto(out *NodeAddressConfig) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAddressConfig.
func (in *NodeAddressConfig) DeepCopy() *NodeAddressConfig {
	if in == nil {
		return nil
	}
	out := new(NodeAddressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkCluster) DeepCopyInto(out *VirtinkCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkCluster.
func (in *VirtinkCluster) DeepCopy() *VirtinkCluster {
	if in == nil {
		return nil
	}
	out := new(VirtinkCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtinkCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkClusterList) DeepCopyInto(out *VirtinkClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtinkCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkClusterList.
func (in *VirtinkClusterList) DeepCopy() *VirtinkClusterList {
	if in == nil {
		return nil
	}
	out := new(VirtinkClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtinkClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkClusterSpec) DeepCopyInto(out *VirtinkClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if in.ControlPlaneServiceType != nil {
		in, out := &in.ControlPlaneServiceType, &out.ControlPlaneServiceType
		*out = new(v1.ServiceType)
		**out = **in
	}
	if in.InfraClusterSecretRef != nil {
		in, out := &in.InfraClusterSecretRef, &out.InfraClusterSecretRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.NodeAddressConfig != nil {
		in, out := &in.NodeAddressConfig, &out.NodeAddressConfig
		*out = new(NodeAddressConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkClusterSpec.
func (in *VirtinkClusterSpec) DeepCopy() *VirtinkClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VirtinkClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkClusterStatus) DeepCopyInto(out *VirtinkClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkClusterStatus.
func (in *VirtinkClusterStatus) DeepCopy() *VirtinkClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VirtinkClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkMachine) DeepCopyInto(out *VirtinkMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkMachine.
func (in *VirtinkMachine) DeepCopy() *VirtinkMachine {
	if in == nil {
		return nil
	}
	out := new(VirtinkMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtinkMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkMachineList) DeepCopyInto(out *VirtinkMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtinkMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkMachineList.
func (in *VirtinkMachineList) DeepCopy() *VirtinkMachineList {
	if in == nil {
		return nil
	}
	out := new(VirtinkMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtinkMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkMachineSpec) DeepCopyInto(out *VirtinkMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	in.VMSpec.DeepCopyInto(&out.VMSpec)
	if in.VolumeTemplates != nil {
		in, out := &in.VolumeTemplates, &out.VolumeTemplates
		*out = make([]VolumeTemplateSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkMachineSpec.
func (in *VirtinkMachineSpec) DeepCopy() *VirtinkMachineSpec {
	if in == nil {
		return nil
	}
	out := new(VirtinkMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkMachineStatus) DeepCopyInto(out *VirtinkMachineStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkMachineStatus.
func (in *VirtinkMachineStatus) DeepCopy() *VirtinkMachineStatus {
	if in == nil {
		return nil
	}
	out := new(VirtinkMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkMachineTemplate) DeepCopyInto(out *VirtinkMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkMachineTemplate.
func (in *VirtinkMachineTemplate) DeepCopy() *VirtinkMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(VirtinkMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtinkMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkMachineTemplateList) DeepCopyInto(out *VirtinkMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtinkMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkMachineTemplateList.
func (in *VirtinkMachineTemplateList) DeepCopy() *VirtinkMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(VirtinkMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtinkMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkMachineTemplateSpec) DeepCopyInto(out *VirtinkMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkMachineTemplateSpec.
func (in *VirtinkMachineTemplateSpec) DeepCopy() *VirtinkMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(VirtinkMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkMachineTemplateSpecTemplate) DeepCopyInto(out *VirtinkMachineTemplateSpecTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkMachineTemplateSpecTemplate.
func (in *VirtinkMachineTemplateSpecTemplate) DeepCopy() *VirtinkMachineTemplateSpecTemplate {
	if in == nil {
		return nil
	}
	out := new(VirtinkMachineTemplateSpecTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtinkMachineTemplateStatus) DeepCopyInto(out *VirtinkMachineTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtinkMachineTemplateStatus.
func (in *VirtinkMachineTemplateStatus) DeepCopy() *VirtinkMachineTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(VirtinkMachineTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeTemplateSource) DeepCopyInto(out *VolumeTemplateSource) {
	*out = *in
	if in.DataVolume != nil {
		in, out := &in.DataVolume, &out.DataVolume
		*out = new(VolumeTemplateSourceDataVolume)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeTemplateSource.
func (in *VolumeTemplateSource) DeepCopy() *VolumeTemplateSource {
	if in == nil {
		return nil
	}
	out := new(VolumeTemplateSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeTemplateSourceDataVolume) DeepCopyInto(out *VolumeTemplateSourceDataVolume) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeTemplateSourceDataVolume.
func (in *VolumeTemplateSourceDataVolume) DeepCopy() *VolumeTemplateSourceDataVolume {
	if in == nil {
		return nil
	}
	out := new(VolumeTemplateSourceDataVolume)
	in.DeepCopyInto(out)
	return out
}
