apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: sample
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.112.0.0/12"]
    pods:
      cidrBlocks: ["10.17.0.0/16"]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: sample-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VirtinkCluster
    name: sample
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VirtinkCluster
metadata:
  name: sample
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: sample-cp
spec:
  replicas: 3
  version: 1.24.0
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: VirtinkMachineTemplate
      name: sample-cp
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: virtink://{{ ds.meta_data.instance_id }}
        ignorePreflightErrors:
          - SystemVerification
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: virtink://{{ ds.meta_data.instance_id }}
        ignorePreflightErrors:
          - SystemVerification
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VirtinkMachineTemplate
metadata:
  name: sample-cp
spec:
  template:
    spec:
      vmSpec:
        runPolicy: Once
        readinessProbe:
          httpGet:
            scheme: HTTPS
            port: 6443
            path: /readyz
        instance:
          cpu:
            sockets: 1
            coresPerSocket: 2
          memory:
            size: 2Gi
          kernel:
            image: smartxworks/capch-kernel-5.15.12
            cmdline: console=ttyS0 root=/dev/vda rw
          disks:
            - name: rootfs
          interfaces:
            - name: pod
        volumes:
          - name: rootfs
            containerRootfs:
              image: smartxworks/capch-rootfs-1.24.0
              size: 4Gi
        networks:
          - name: pod
            pod: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: sample-md
spec:
  clusterName: sample
  replicas: 3
  selector: {}
  template:
    spec:
      clusterName: sample
      version: 1.24.0
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: sample-md
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VirtinkMachineTemplate
        name: sample-md
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: sample-md
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            provider-id: virtink://{{ ds.meta_data.instance_id }}
          ignorePreflightErrors:
            - SystemVerification
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VirtinkMachineTemplate
metadata:
  name: sample-md
spec:
  template:
    spec:
      vmSpec:
        runPolicy: Once
        instance:
          cpu:
            sockets: 1
            coresPerSocket: 2
          memory:
            size: 2Gi
          kernel:
            image: smartxworks/capch-kernel-5.15.12
            cmdline: console=ttyS0 root=/dev/vda rw
          disks:
            - name: rootfs
          interfaces:
            - name: pod
        volumes:
          - name: rootfs
            containerRootfs:
              image: smartxworks/capch-rootfs-1.24.0
              size: 4Gi
        networks:
          - name: pod
            pod: {}
