name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v1
        with:
          username: smartxrocks
          password: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: docker.io/smartxworks/capch-controller:${{ steps.get_version.outputs.version }}
          platforms: linux/amd64,linux/arm64
          push: true

      - run: |
          curl -sLo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x /tmp/skaffold
          /tmp/skaffold render --default-repo=docker.io/smartxworks --offline=true > infrastructure-components.yaml

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            infrastructure-components.yaml
            metadata.yaml
            templates/cluster-template.yaml
            templates/cluster-template-external.yaml
